name: My First Workflow 

on: 
  push:
    branches: 
      - main 
    paths: 
      - 'labs/**'
    
jobs:
  my-first-job:
    name: Our first Job

    runs-on: ubuntu-latest 

    steps:

          - uses: actions/checkout@v4

          - run: echo "Hello World" 
        
          
