name: My First Workflow 

on: 
  push:
    branches: 
      - main 

    
jobs:
  my-first-job:
    name: Our first Job

    runs-on: ubuntu-latest 

    steps:

          - uses: actions/checkout@v4

          - run: echo "Hello World" 
        # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
          - name: Hello world
            uses: actions/hello-world-javascript-action@main
            with:
              who-to-greet: "Ohio Department of Transportation"
            id: hello
      # This step prints an output (time) from the previous step's action.
          - name: Echo the greeting's time
            run: echo 'The time was ${{ steps.hello.outputs.time }}.'   
